final int PACKET_OK = 0;
final int PACKET_ERROR = 0xFF;
final int PACKET_EOF = 0xFE;

final int CLIENT_LONG_PASSWORD = 1; /* new more secure passwords */
final int CLIENT_FOUND_ROWS = 2; /* Found instead of affected rows */
final int CLIENT_LONG_FLAG = 4; /* Get all column flags */
final int CLIENT_CONNECT_WITH_DB = 8; /* One can specify db on connect */
final int CLIENT_NO_SCHEMA = 16;  /* Don't allow database.table.column */
final int CLIENT_COMPRESS = 32;  /* Can use compression protocol */
final int CLIENT_ODBC = 64;  /* Odbc client */
final int CLIENT_LOCAL_FILES = 128; /* Can use LOAD DATA LOCAL */
final int CLIENT_IGNORE_SPACE = 256; /* Ignore spaces before '(' */
final int CLIENT_PROTOCOL_41 = 512; /* New 4.1 protocol */
final int CLIENT_INTERACTIVE = 1024;  /* This is an interactive client */
final int CLIENT_SSL = 2048;  /* Switch to SSL after handshake */
final int CLIENT_IGNORE_SIGPIPE = 4096;    /* IGNORE sigpipes */
final int CLIENT_TRANSACTIONS = 8192;  /* Client knows about transactions */
final int CLIENT_RESERVED = 16384;   /* Old flag for 4.1 protocol  */
final int CLIENT_SECURE_CONNECTION = 32768;  /* New 4.1 authentication */
final int CLIENT_MULTI_STATEMENTS = 65536;   /* Enable/disable multi-stmt support */
final int CLIENT_MULTI_RESULTS = 131072;  /* Enable/disable multi-results */

final int SERVER_STATUS_IN_TRANS = 1; /* Transaction has started */
final int SERVER_STATUS_AUTOCOMMIT = 2; /* Server in auto_commit mode */

final int COM_SLEEP = 0x00; // (none, this is an internal thread state)
final int COM_QUIT = 0x01; // mysql_close
final int COM_INIT_DB = 0x02; // mysql_select_db 
final int COM_QUERY = 0x03; // mysql_real_query
final int COM_FIELD_LIST = 0x04; // mysql_list_fields
final int COM_CREATE_DB = 0x05; // mysql_create_db (deprecated)
final int COM_DROP_DB = 0x06; // mysql_drop_db (deprecated)
final int COM_REFRESH = 0x07; // mysql_refresh
final int COM_SHUTDOWN = 0x08; // mysql_shutdown
final int COM_STATISTICS = 0x09; // mysql_stat
final int COM_PROCESS_INFO = 0x0a; // mysql_list_processes
final int COM_CONNECT = 0x0b; // (none, this is an internal thread state)
final int COM_PROCESS_KILL = 0x0c; // mysql_kill
final int COM_DEBUG = 0x0d; // mysql_dump_debug_info
final int COM_PING = 0x0e; // mysql_ping
final int COM_TIME = 0x0f; // (none, this is an internal thread state)
final int COM_DELAYED_INSERT = 0x10; // (none, this is an internal thread state)
final int COM_CHANGE_USER = 0x11; // mysql_change_user
final int COM_BINLOG_DUMP = 0x12; // sent by the slave IO thread to request a binlog
final int COM_TABLE_DUMP = 0x13; // LOAD TABLE ... FROM MASTER (deprecated)
final int COM_CONNECT_OUT = 0x14; // (none, this is an internal thread state)
final int COM_REGISTER_SLAVE = 0x15; // sent by the slave to register with the master (optional)
final int COM_STMT_PREPARE = 0x16; // mysql_stmt_prepare
final int COM_STMT_EXECUTE = 0x17; // mysql_stmt_execute
final int COM_STMT_SEND_LONG_DATA = 0x18; // mysql_stmt_send_long_data
final int COM_STMT_CLOSE = 0x19; // mysql_stmt_close
final int COM_STMT_RESET = 0x1a; // mysql_stmt_reset
final int COM_SET_OPTION = 0x1b; // mysql_set_server_option
final int COM_STMT_FETCH = 0x1c; // mysql_stmt_fetch
