#!/bin/sh
SCRIPT=$(readlink -f $0)
SCRIPTPATH=$(dirname $SCRIPT)
cd $SCRIPTPATH/..

#dartdoc --output ../sqljocky_pages/docs --package-root packages \
#--exclude-lib logging,buffer,buffered_socket,crypto,unmodifiable_collection,constants \
#lib/sqljocky.dart lib/constants.dart lib/utils.dart

dartdoc --output docs
 #--package-root
#packages \
#--exclude-lib logging,buffer,buffered_socket,crypto,unmodifiable_collection,constants \
#lib/sqljocky.dart lib/constants.dart lib/utils.dart
